# Generated by Django 4.2.5 on 2023-09-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': {('can_view_customers', 'Can view customers')}, 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
