# Generated by Django 4.2.5 on 2023-09-12 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0003_rename_theme_message_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='start_sending_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 12, 51, 22, 303642), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_sending_time',
            field=models.TimeField(blank=True, default=datetime.time(12, 51, 22, 303669), null=True, verbose_name='время рассылки'),
        ),
    ]
