# Generated by Django 4.2.5 on 2023-09-12 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0008_alter_sending_start_sending_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrySending',
            new_name='Log',
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_sending_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 13, 19, 53, 484628), verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='sending',
            name='start_sending_time',
            field=models.TimeField(blank=True, default=datetime.time(13, 19, 53, 484653), null=True, verbose_name='время рассылки'),
        ),
    ]
